
server:
  port: 8082

#eueka 主机名
eureka:
  instance:
    hostname: eureka-service
  client:
    #不注册自己
    register-with-eureka: false
    #获取服务
    fetch-registry: false
    #提供者和消费者的注册地址
    service-url:
      defaultZone: http://localhost:8082/eureka/
