
server:
  port: 8761

#eueka \u4E3B\u673A\u540D
eureka:
  instance:
    hostname: eureka-service
  #\u4E0D\u6CE8\u518C\u81EA\u5DF1
  client:
    register-with-eureka: false
    #\u83B7\u53D6\u670D\u52A1
    fetch-registry: false
    #\u63D0\u4F9B\u8005\u548C\u6D88\u8D39\u8005\u7684\u6CE8\u518C\u5730\u5740
    service-url:
      defaultZone: http://localhost:8761/eureka/
